name: tarifitino
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  flutter_launcher_icons: ^0.14.3
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_fonts: ^6.2.1
  lucide_icons_flutter: ^2.0.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imagesRif/hoceima/
    - assets/imagesRif/nador/