name: tarifitino
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  flutter_launcher_icons: ^0.14.3
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_fonts: ^6.2.1
  lucide_icons_flutter: ^2.0.1
  carousel_slider: ^5.0.0
  permission_handler: ^11.4.0
  google_sign_in: ^6.2.2
  firebase_storage: ^12.4.4
  path_provider: ^2.1.2
  flutter_sound: ^9.2.13
  audioplayers: ^6.4.0
  # google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/imagesRif/hoceima/
    - assets/imagesRif/nador/
    - assets/imagesRif/imzouren/
    - assets/imagesRif/targuist/
    - assets/imagesRif/melilla/
    - assets/imagesRif/montagne/
    - assets/histoireRif/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png