// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYlayQmvrED39qNNlOWFzjcr76Bm2WmAE',
    appId: '1:938262438862:web:ab46a8979713176a9c019f',
    messagingSenderId: '938262438862',
    projectId: 'tarifitino-f5a5b',
    authDomain: 'tarifitino-f5a5b.firebaseapp.com',
    storageBucket: 'tarifitino-f5a5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATTdVujoDoF0FdrGfRlTPL5O2BmVxeBJ8',
    appId: '1:938262438862:android:67eaf017d2a740769c019f',
    messagingSenderId: '938262438862',
    projectId: 'tarifitino-f5a5b',
    storageBucket: 'tarifitino-f5a5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1SBA1_40A0TDy3d3ajGi8OQnEQ484nlI',
    appId: '1:938262438862:ios:f84d546d8094f3c49c019f',
    messagingSenderId: '938262438862',
    projectId: 'tarifitino-f5a5b',
    storageBucket: 'tarifitino-f5a5b.firebasestorage.app',
    iosBundleId: 'com.example.tarifitino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1SBA1_40A0TDy3d3ajGi8OQnEQ484nlI',
    appId: '1:938262438862:ios:f84d546d8094f3c49c019f',
    messagingSenderId: '938262438862',
    projectId: 'tarifitino-f5a5b',
    storageBucket: 'tarifitino-f5a5b.firebasestorage.app',
    iosBundleId: 'com.example.tarifitino',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYlayQmvrED39qNNlOWFzjcr76Bm2WmAE',
    appId: '1:938262438862:web:c58b6e3f6cdf8d5b9c019f',
    messagingSenderId: '938262438862',
    projectId: 'tarifitino-f5a5b',
    authDomain: 'tarifitino-f5a5b.firebaseapp.com',
    storageBucket: 'tarifitino-f5a5b.firebasestorage.app',
  );
}
